import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "../app/components/ClientLayout/page"; // Importamos el componente de cliente
import { AuthProvider } from './src/contexts/AuthContext';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cine Impar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">          
        <body className={inter.className}>

            {children}

        </body>
      </html>
    </AuthProvider>
  );
}
