import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "./components/ClientLayout/clientlayout"; // Importamos el componente de cliente
import { AuthProvider } from './src/contexts/AuthContext';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cine Impar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthProvider>
      <html lang="en">          
        <body className={inter.className}>
        <AuthProvider>
            {children}
        </AuthProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
